repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      # запрет размещения докстрингов перед кодом
      - id: check-docstring-first
      - id: check-case-conflict
      # запрет на коммит неразрешенных конфликтов мерджа гита
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [xml]
      # запрет коммитов в мастер и в релиз
      - id: no-commit-to-branch
        args: [ --branch=master, --branch=release ]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'
    hooks:
      - id: autopep8
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
