services:

  # shard 1 replicas (3 count)
  mongors1n1:
    container_name: mongors1n1
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/data/data1:/data/db
      - ../../mongo/scripts:/scripts


  mongors1n2:
    container_name: mongors1n2
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/data/data2:/data/db
      - ../../mongo/scripts:/scripts

  mongors1n3:
    container_name: mongors1n3
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27037:27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/data/data3:/data/db
      - ../../mongo/scripts:/scripts

  # shard 2 replicas (3 count)
  mongors2n1:
    container_name: mongors2n1
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27047:27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/data/data4:/data/db
      - ../../mongo/scripts:/scripts

  mongors2n2:
    container_name: mongors2n2
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27057:27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/data/data5:/data/db
      - ../../mongo/scripts:/scripts

  mongors2n3:
    container_name: mongors2n3
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27067:27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/data/data6:/data/db
      - ../../mongo/scripts:/scripts

  # config servers
  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/config/config1:/data/db
      - ../../mongo/scripts:/scripts

  mongocfg2:
    container_name: mongocfg2
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/config/config2:/data/db
      - ../../mongo/scripts:/scripts

  mongocfg3:
    container_name: mongocfg3
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/config/config3:/data/db
      - ../../mongo/scripts:/scripts

  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/scripts:/scripts

  mongos2:
    container_name: mongos2
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    ports:
      - 27020:27017
    expose:
      - "27017"
    volumes:
      - ../../mongo/etc/localtime:/etc/localtime:ro
      - ../../mongo/scripts:/scripts
