version: "3.9"

networks:
  yp_network:
    name: yp_network
    external: true

services:
  ugc_gate:
    build:
      context: ../../
      dockerfile: devops/docker/gate/Dockerfile
      target: develop
    container_name: yp_ugc_gate_api
    user: "gatekeeper"
    restart: always
    env_file:
      - ../gate/.env
    networks:
      - yp_network

  ugc_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: yp_ugc_kafka
    env_file:
      - ../kafka/.env
    depends_on:
      - ugc_zookeeper
    networks:
      - yp_network

  ugc_zookeeper:
    image: zookeeper:3.5
    container_name: yp_ugc_zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - yp_network
