version: "3.9"

networks:
  yp_network:
    name: yp_network
    external: true

services:
  ugc_gate_api:
    build:
      context: ../../
      dockerfile: devops/docker/gate/Dockerfile
      target: develop
    container_name: yp_ugc_gate_api
    user: "gatekeeper"
    restart: always
    ports:
      - "8004:8000"
    env_file:
      - ../../devops/gate/.env
    networks:
      - yp_network

  ugc_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: yp_ugc_kafka
#    ports:
#      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: yp_ugc_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ugc_kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - ugc_zookeeper
    networks:
      - yp_network

  ugc_zookeeper:
    image: zookeeper:3.5
    container_name: yp_ugc_zookeeper
#    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - yp_network
