version: "3.9"

services:
  ugc_gate:
    build:
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "--reload", "main:app"]
    ports:
      - "8004:8000"
    volumes:
      - ../../:/usr/src/app
  ugc_kafka:
    ports:
      - 29092:29092