version: "3.9"

networks:
  yp_network:
    name: yp_network
    external: true

services:
  api:
    build:
      target: develop
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "--reload", "gate.main:app", "--log-config", "gate/log.ini"]
    ports:
      - 8100:8000
    volumes:
      - ../../../src:/usr/src
    networks:
      - yp_network

  nginx:
    image: nginx:1.19.2
    volumes:
      - /tmp/logs/nginx/:/var/log/nginx/
      - ../../nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../nginx/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api
    ports:
      - 8080:80
    networks:
      - yp_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.2
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ../../logging/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - api
      - nginx
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash
    networks:
      - yp_network

  filebeat-api:
    image: docker.elastic.co/beats/filebeat:7.3.2
    volumes:
      - ../../../src/gate/logs/:/var/log/gate-api/logs/
      - ../../logging/filebeat-api.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - api
      - nginx
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash
    networks:
      - yp_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - /tmp/logs/nginx/:/var/log/nginx/:ro
      - ../../logging/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    networks:
      - yp_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
    networks:
      - yp_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - yp_network
