filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/gate-api/logs/*.log
  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
